id    = "plaquette"
files = [
    "../BOTH16x16x16x16wilson_flow.jld2",
    "../BOTH20x20x20x20wilson_flow.jld2",
    "../BOTH24x24x24x24wilson_flow.jld2"
]
uids  = [
    "16^4",
    "20^4",
    "24^4"
]

[Simulation]
betas = [5.76, 5.86, 5.96]
flow  = "wilson"

[Analysis]
xi = 1     # Plaquette weight: xi * pl + (1 - xi) * cl
rg = false # Renormalization group improvement

[Action_density]
names  = ["tc", "t0", "tw"]
values = [ 0.2,  0.3,  0.4]

[Derivative_action_density]
names  = ["w0"]
values = [ 0.3]
